/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CakeChuff.java
 *
 * Created on 21-may-2009, 1:54:40
 */

package cc;

import java.awt.Color;
import java.io.File;
import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import com.jme.app.AbstractGame.ConfigShowMode;

import cc.automatons.Automaton;
import cc.automatons.BlisterAutomaton;
import cc.automatons.CakeAutomaton;
import cc.automatons.MasterAutomaton;
import cc.automatons.QCAutomaton;
import cc.simulation.state.ControlInterface;
import cc.simulation.subsystems.Factory;

/**
 * Executing the rest of the application
 * Start and finish every thread
 */
public class CakeChuff extends javax.swing.JFrame {

	private static Logger logger = Logger.getLogger(CakeChuff.class.getName());
    // Subsystems IDs
    private final int SCADA=1;
    private final int MASTER=2;
    private final int CAKES=3;
    private final int BLISTERS=4;
    private final int QUALITY=5;
    
    private static Factory factory;
    
    private boolean scandaRunning = false;

    // Threads of every subsystem
    private Automaton masterAutomaton = null;
    private Automaton cakesAutomaton = null;
    private Automaton blisterAutomaton = null;
    private Automaton qualityAutomaton = null;
    /** Creates new form CakeChuff */
    public CakeChuff() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RunEveryThingButton = new javax.swing.JToggleButton();
        RunMasterButton = new javax.swing.JToggleButton();
        RunCakeSubsystemButton = new javax.swing.JToggleButton();
        RunBlisterSubsystemButton = new javax.swing.JToggleButton();
        RunQualitySubystemButton = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CakeChuff - Threads");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Threads"));
        jPanel1.setLayout(new java.awt.GridLayout(5, 0));

        RunEveryThingButton.setText("Run All the Systems");
        RunEveryThingButton.setMaximumSize(new java.awt.Dimension(100, 23));
        RunEveryThingButton.setMinimumSize(new java.awt.Dimension(100, 23));
        RunEveryThingButton.setPreferredSize(new java.awt.Dimension(140, 50));
        RunEveryThingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunEveryThingButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RunEveryThingButton);

        RunMasterButton.setForeground(new java.awt.Color(255, 102, 102));
        RunMasterButton.setText("Master Subsystem is OFF");
        RunMasterButton.setMaximumSize(new java.awt.Dimension(100, 23));
        RunMasterButton.setMinimumSize(new java.awt.Dimension(100, 23));
        RunMasterButton.setPreferredSize(new java.awt.Dimension(100, 23));
        RunMasterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunMasterButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RunMasterButton);

        RunCakeSubsystemButton.setForeground(new java.awt.Color(255, 102, 102));
        RunCakeSubsystemButton.setText("Cake Subsystem is OFF");
        RunCakeSubsystemButton.setMaximumSize(new java.awt.Dimension(100, 23));
        RunCakeSubsystemButton.setMinimumSize(new java.awt.Dimension(100, 23));
        RunCakeSubsystemButton.setPreferredSize(new java.awt.Dimension(100, 23));
        RunCakeSubsystemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunCakeSubsystemButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RunCakeSubsystemButton);

        RunBlisterSubsystemButton.setForeground(new java.awt.Color(255, 102, 102));
        RunBlisterSubsystemButton.setText("Blisters Subsystem is OFF");
        RunBlisterSubsystemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunBlisterSubsystemButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RunBlisterSubsystemButton);

        RunQualitySubystemButton.setForeground(new java.awt.Color(255, 102, 102));
        RunQualitySubystemButton.setText("Quality Subsystem is OFF");
        RunQualitySubystemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunQualitySubystemButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RunQualitySubystemButton);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cameras"));
        jPanel2.setLayout(new java.awt.GridLayout(3, 2));

        jButton1.setText("Main");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton3.setText("Cakes");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        jButton2.setText("Blisters");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton4.setText("Quality");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        jButton5.setText("Mouse Cam");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RunCakeSubsystemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunCakeSubsystemButtonActionPerformed
    	if( !scandaRunning ) startSubsystem(SCADA);
        if(RunEveryThingButton.isEnabled()) RunEveryThingButton.setEnabled(false);
        if(RunCakeSubsystemButton.isSelected()){
            startSubsystem(CAKES);
            RunCakeSubsystemButton.setText("Cakes Subsystem is ON");
            RunCakeSubsystemButton.setForeground(Color.GREEN);
            RunCakeSubsystemButton.setSelected(true);
        } else {
            stopSubsystem(CAKES);
            RunCakeSubsystemButton.setText("Cakes Subsystem is OFF");
            RunCakeSubsystemButton.setForeground(Color.RED);
            RunCakeSubsystemButton.setSelected(false);
        }
}//GEN-LAST:event_RunCakeSubsystemButtonActionPerformed

    private void RunBlisterSubsystemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunBlisterSubsystemButtonActionPerformed
    	if( !scandaRunning ) startSubsystem(SCADA);
        if(RunEveryThingButton.isEnabled()) RunEveryThingButton.setEnabled(false);
        if(RunBlisterSubsystemButton.isSelected()){
            startSubsystem(BLISTERS);
            RunBlisterSubsystemButton.setText("Blisters Subsystem is ON");
            RunBlisterSubsystemButton.setForeground(Color.GREEN);
            RunBlisterSubsystemButton.setSelected(true);
        } else {
            stopSubsystem(BLISTERS);
            RunBlisterSubsystemButton.setText("Blisters Subsystem is OFF");
            RunBlisterSubsystemButton.setForeground(Color.RED);
            RunBlisterSubsystemButton.setSelected(false);
        }
}//GEN-LAST:event_RunBlisterSubsystemButtonActionPerformed

    private void RunEveryThingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunEveryThingButtonActionPerformed
    	if( !scandaRunning ) startSubsystem(SCADA);
        startSubsystem(MASTER);
        RunMasterButton.setText("Master is ON");
        RunMasterButton.setForeground(Color.GREEN);
        RunMasterButton.setSelected(true);
        startSubsystem(CAKES);
        RunCakeSubsystemButton.setText("Cakes Subystem is ON");
        RunCakeSubsystemButton.setForeground(Color.GREEN);
        RunCakeSubsystemButton.setSelected(true);
        startSubsystem(BLISTERS);
        RunBlisterSubsystemButton.setText("Blisters Subystem is ON");
        RunBlisterSubsystemButton.setForeground(Color.GREEN);
        RunBlisterSubsystemButton.setSelected(true);
        startSubsystem(QUALITY);
        RunQualitySubystemButton.setText("Quality Subystem is ON");
        RunQualitySubystemButton.setForeground(Color.GREEN);
        RunQualitySubystemButton.setSelected(true);

        RunEveryThingButton.setEnabled(false);
}//GEN-LAST:event_RunEveryThingButtonActionPerformed

    private void RunMasterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunMasterButtonActionPerformed
    	if( !scandaRunning ) startSubsystem(SCADA);
        if(RunEveryThingButton.isEnabled()) RunEveryThingButton.setEnabled(false);
        if(RunMasterButton.isSelected()){
            startSubsystem(MASTER);
            RunMasterButton.setText("Master is ON");
            RunMasterButton.setForeground(Color.GREEN);
            RunMasterButton.setSelected(true);
        } else {
            stopSubsystem(MASTER);
            RunMasterButton.setText("Master is OFF");
            RunMasterButton.setForeground(Color.RED);
            RunMasterButton.setSelected(false);
        }
    }//GEN-LAST:event_RunMasterButtonActionPerformed

    private void RunQualitySubystemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunQualitySubystemButtonActionPerformed
    	if( !scandaRunning ) startSubsystem(SCADA);
        if(RunEveryThingButton.isEnabled()) RunEveryThingButton.setEnabled(false);
        if(RunQualitySubystemButton.isSelected()){
            startSubsystem(QUALITY);
            RunQualitySubystemButton.setText("Quality Subsystem is ON");
            RunQualitySubystemButton.setForeground(Color.GREEN);
            RunQualitySubystemButton.setSelected(true);
        } else {
            stopSubsystem(QUALITY);
            RunQualitySubystemButton.setText("Quality Subsystem is ON");
            RunQualitySubystemButton.setForeground(Color.RED);
            RunQualitySubystemButton.setSelected(false);
        }
    }//GEN-LAST:event_RunQualitySubystemButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        factory.loadCamera(factory.CAMERA_WHOLE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    	factory.loadCamera(factory.CAMERA_CAKESUB);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    	factory.loadCamera(factory.CAMERA_BLISTERSUB);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    	factory.loadCamera(factory.CAMERA_QASUB);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        factory.loadCamera(factory.CAMERA_MOUSE);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void startSubsystem(int id){
        switch(id){
            case MASTER:
            	
            	masterAutomaton = new MasterAutomaton("localhost",9009,9008,
            								 "localhost",9000,9001,
            								 "localhost",9003,9002,
            								 "localhost",9005,9004);
                break;
            case SCADA:
            	scandaRunning = true;
            	java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        try {
                            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                        } catch (ClassNotFoundException ex) {
                            Logger.getLogger(ControlInterface.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (InstantiationException ex) {
                            Logger.getLogger(ControlInterface.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IllegalAccessException ex) {
                            Logger.getLogger(ControlInterface.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (UnsupportedLookAndFeelException ex) {
                            Logger.getLogger(ControlInterface.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        new ControlInterface().setVisible(true);
                    }
                });
                break;
            case CAKES:            	
            	cakesAutomaton = new CakeAutomaton(9001,9000,"localhost");            	
                break;
            case BLISTERS:
            	blisterAutomaton = new BlisterAutomaton(9002,9003,"localhost");        		
                break;
            case QUALITY:
            	qualityAutomaton = new QCAutomaton(9004,9005,"localhost");
                break;
        }
    }

    private void stopSubsystem(int id){
        switch(id){
            case MASTER:
            	masterAutomaton.destroyAutomaton();
                break;
            case SCADA:
                break;
            case CAKES:
            	cakesAutomaton.destroyAutomaton();
                break;
            case BLISTERS:
            	blisterAutomaton.destroyAutomaton();
                break;
            case QUALITY:
            	qualityAutomaton.destroyAutomaton();
                break;
        }
    }
    /**
    * @param args The command line arguments
    */
    public static void main(String args[]) {
    	
    	try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            logger.log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
        	logger.log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
        	logger.log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
        	logger.log(Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CakeChuff().setVisible(true);
            }
        });
        
        factory = new Factory();
		try {
			factory.setConfigShowMode(ConfigShowMode.AlwaysShow, new File("")
					.toURI().toURL());
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}

		factory.start();        	
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton RunBlisterSubsystemButton;
    private javax.swing.JToggleButton RunCakeSubsystemButton;
    private javax.swing.JToggleButton RunEveryThingButton;
    private javax.swing.JToggleButton RunMasterButton;
    private javax.swing.JToggleButton RunQualitySubystemButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
