/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FactoryInterface.java
 *
 * Created on 27-mar-2009, 0:13:19
 */

package cc.simulation.state;

import java.beans.DesignMode;
import java.util.Observable;
import java.util.Observer;
import java.io.*;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import cc.simulation.elements.LightSensor;
import cc.simulation.elements.TouchSensor;

/**
 *
 * @author diego
 */
public class FactoryInterface extends javax.swing.JFrame implements Observer{
	
	// State
	private SystemState _systemState=null;
	private CakeSubsystemState _cakeSubState=null;
	private BlisterSubsystemState _blisterSubState=null;
	private QualitySubsystemState _qualitySubState=null;
	private Robot1State _robot1State=null;




        
    /** Creates new form FactoryInterface */
    public FactoryInterface() {
        // ^ Just notify no observer
        
    	/*_systemState = SystemState.getInstance();
    	_cakeSubState = CakeSubsystemState.getInstance();
    	_cakeSubState.addObserver(this);
    	_blisterSubState = BlisterSubsystemState.getInstance();
    	_blisterSubState.addObserver(this);
    	_qualitySubState = QualitySubsystemState.getInstance();
    	_qualitySubState.addObserver(this);
    	_robot1State = Robot1State.getInstance();
    	_robot1State.addObserver(this);*/
    	    	
        initComponents();
         //this.setIconImage(new javax.swing.ImageIcon("cc/Images/iconCakeChuff.png").getImage());
        
        /*InputStream imgStream = this.getClass().getResourceAsStream("cc/Images/iconCakeChuff.PNG");
        java.awt.image.BufferedImage bi;
        try {
            bi = javax.imageio.ImageIO.read(imgStream);
            this.setIconImage(new javax.swing.ImageIcon(bi).getImage());
        } catch (IOException ex) {
            Logger.getLogger(FactoryInterface.class.getName()).log(Level.SEVERE, null, ex);
        }*/

         
        
        
        try {
			UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
			SwingUtilities.updateComponentTreeUI(this);
			this.pack();
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (InstantiationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IllegalAccessException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (UnsupportedLookAndFeelException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }
    
    private void changeLabelColor(JLabel label, boolean detected)
    {
    	if( detected ){
       		label.setText("Detection");
    		label.setForeground(new java.awt.Color(0, 204, 0));
    	} else {
    		label.setText("None");
    		label.setForeground(new java.awt.Color(204, 0, 0));
    	}
    		
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPane = new javax.swing.JTabbedPane();
        ControlTab = new javax.swing.JPanel();
        BlisterPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        spinnerBeltSpeed2 = new javax.swing.JSpinner();
        spinnerBeltLenght2 = new javax.swing.JSpinner();
        CakePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        spinnerBeltLenght1 = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        spinnerChoc = new javax.swing.JSpinner();
        spinnerBeltSpeed1 = new javax.swing.JSpinner();
        spinnerCakesCapacity = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        spinnerCaramel = new javax.swing.JSpinner();
        QualityPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        spinnerBeltSpeed3 = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        spinnerBeltLenght3 = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        spinnerRobot2Pick = new javax.swing.JSpinner();
        jLabel23 = new javax.swing.JLabel();
        spinnerSealingTIme = new javax.swing.JSpinner();
        spinnerFailRange = new javax.swing.JSpinner();
        jLabel26 = new javax.swing.JLabel();
        StartButton = new javax.swing.JButton();
        StopButton = new javax.swing.JButton();
        EmergencyButton = new javax.swing.JButton();
        BlisterPanel1 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        spinnerRobot1PickCake = new javax.swing.JSpinner();
        jLabel25 = new javax.swing.JLabel();
        spinnerRobot1MoveBlister = new javax.swing.JSpinner();
        ResetButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        ControlTab1 = new javax.swing.JPanel();
        LastExecution = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        okblisters = new javax.swing.JLabel();
        koblisters = new javax.swing.JLabel();
        History = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        okcake = new javax.swing.JLabel();
        kocake = new javax.swing.JLabel();
        CakePanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        starts = new javax.swing.JLabel();
        stops = new javax.swing.JLabel();
        emerstops = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        cicles = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        timelaststartup = new javax.swing.JLabel();
        workingtime = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        GeneratePDF = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CakeChuff Control Panel");
        setIconImage(getIconImage());
        setName("CakechuffControlPanel"); // NOI18N
        setResizable(false);

        BlisterPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Blister Subsystem", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jLabel11.setText("Conveyor Belt Speed:");

        jLabel12.setText("Conveyor Belt Lenght (meters):");

        spinnerBeltSpeed2.setName("beltspeed2"); // NOI18N
        spinnerBeltSpeed2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerBeltspeed2StateChanged(evt);
            }
        });

        spinnerBeltLenght2.setName("beltlenght2l"); // NOI18N
        spinnerBeltLenght2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerbeltlenght2StateChanged(evt);
            }
        });

        javax.swing.GroupLayout BlisterPanelLayout = new javax.swing.GroupLayout(BlisterPanel);
        BlisterPanel.setLayout(BlisterPanelLayout);
        BlisterPanelLayout.setHorizontalGroup(
            BlisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlisterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BlisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BlisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinnerBeltLenght2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerBeltSpeed2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        BlisterPanelLayout.setVerticalGroup(
            BlisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlisterPanelLayout.createSequentialGroup()
                .addGroup(BlisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(spinnerBeltSpeed2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BlisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(spinnerBeltLenght2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        CakePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cake Subsystem", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jLabel1.setText("Conveyor Belt Speed:");

        jLabel13.setText("Chocolate Valve (secs):");

        spinnerBeltLenght1.setName("beltlenght"); // NOI18N
        spinnerBeltLenght1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerbeltLenght1StateChanged(evt);
            }
        });

        jLabel14.setText("Caramel Valve (secs):");

        spinnerChoc.setName("choc"); // NOI18N
        spinnerChoc.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerChocStateChanged(evt);
            }
        });

        spinnerBeltSpeed1.setName("beltspeed"); // NOI18N
        spinnerBeltSpeed1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerBeltLenght1StateChanged(evt);
            }
        });

        spinnerCakesCapacity.setName("Cakes"); // NOI18N
        spinnerCakesCapacity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerCakesCapacityStateChanged(evt);
            }
        });

        jLabel2.setText("Cakes capacity:");

        jLabel22.setText("Conveyor Belt Lenght (meters):");

        spinnerCaramel.setName("caramel"); // NOI18N
        spinnerCaramel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerCaramelStateChanged(evt);
            }
        });

        javax.swing.GroupLayout CakePanelLayout = new javax.swing.GroupLayout(CakePanel);
        CakePanel.setLayout(CakePanelLayout);
        CakePanelLayout.setHorizontalGroup(
            CakePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CakePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CakePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CakePanelLayout.createSequentialGroup()
                        .addGroup(CakePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CakePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(CakePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(spinnerChoc, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(spinnerBeltLenght1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(spinnerBeltSpeed1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(spinnerCakesCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CakePanelLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerCaramel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        CakePanelLayout.setVerticalGroup(
            CakePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CakePanelLayout.createSequentialGroup()
                .addGroup(CakePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spinnerCakesCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CakePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerBeltSpeed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CakePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerBeltLenght1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CakePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CakePanelLayout.createSequentialGroup()
                        .addComponent(spinnerChoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(CakePanelLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(CakePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spinnerCaramel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        QualityPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quality Subsystem", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jLabel15.setText("Conveyor Belt  Speed:");

        spinnerBeltSpeed3.setName("beltspeed3"); // NOI18N
        spinnerBeltSpeed3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerBeltspeed3StateChanged(evt);
            }
        });

        jLabel17.setText("Sealing Time (secs):");

        spinnerBeltLenght3.setName("beltlenght3"); // NOI18N
        spinnerBeltLenght3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerbeltlenght3Changed(evt);
            }
        });

        jLabel18.setText("Robot: Pick Blister (secs):");

        spinnerRobot2Pick.setName("robot2time"); // NOI18N
        spinnerRobot2Pick.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerRobot1PickStateChanged(evt);
            }
        });

        jLabel23.setText("Failure Range (%):");

        spinnerSealingTIme.setName("sealtime"); // NOI18N
        spinnerSealingTIme.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerSealingTimeStateChanged(evt);
            }
        });

        spinnerFailRange.setName("failrange"); // NOI18N
        spinnerFailRange.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerFailureRangeStateChanged(evt);
            }
        });

        jLabel26.setText("Conveyor Belt Lenght (meters):");

        javax.swing.GroupLayout QualityPanelLayout = new javax.swing.GroupLayout(QualityPanel);
        QualityPanel.setLayout(QualityPanelLayout);
        QualityPanelLayout.setHorizontalGroup(
            QualityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QualityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QualityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QualityPanelLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(spinnerBeltSpeed3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(QualityPanelLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(spinnerSealingTIme, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QualityPanelLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(spinnerBeltLenght3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(QualityPanelLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(spinnerFailRange, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(QualityPanelLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(spinnerRobot2Pick, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        QualityPanelLayout.setVerticalGroup(
            QualityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QualityPanelLayout.createSequentialGroup()
                .addGroup(QualityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(spinnerBeltSpeed3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(QualityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerBeltLenght3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(QualityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(spinnerFailRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(QualityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(spinnerSealingTIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(QualityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(spinnerRobot2Pick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        StartButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        StartButton.setText("Start");
        StartButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 102), 1, true));
        StartButton.setName("start"); // NOI18N
        StartButton.setPreferredSize(new java.awt.Dimension(31, 17));
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });

        StopButton.setFont(new java.awt.Font("Tahoma", 1, 13));
        StopButton.setText("Stop");
        StopButton.setBorder(null);
        StopButton.setName("stop"); // NOI18N
        StopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopButtonActionPerformed(evt);
            }
        });

        EmergencyButton.setBackground(javax.swing.UIManager.getDefaults().getColor("nb.errorForeground"));
        EmergencyButton.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        EmergencyButton.setIcon(new javax.swing.ImageIcon("F:\\SI\\CakeChuff_ui\\CakeChuff\\src\\cc\\Images\\seccion_icono.gif")); // NOI18N
        EmergencyButton.setText("Emergency Stop");
        EmergencyButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(102, 0, 0)));
        EmergencyButton.setName("emergency"); // NOI18N
        EmergencyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmergencyButtonActionPerformed(evt);
            }
        });

        BlisterPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Robot", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jLabel24.setText("Pick Cake (secs):");

        spinnerRobot1PickCake.setName("robotpickcake"); // NOI18N
        spinnerRobot1PickCake.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerRobot1PickCakeStateChanged(evt);
            }
        });

        jLabel25.setText("Move Blister (secs):");

        spinnerRobot1MoveBlister.setName("robotmove"); // NOI18N
        spinnerRobot1MoveBlister.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerRobot1MoveStateChanged(evt);
            }
        });

        javax.swing.GroupLayout BlisterPanel1Layout = new javax.swing.GroupLayout(BlisterPanel1);
        BlisterPanel1.setLayout(BlisterPanel1Layout);
        BlisterPanel1Layout.setHorizontalGroup(
            BlisterPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlisterPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BlisterPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addGap(71, 71, 71)
                .addGroup(BlisterPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spinnerRobot1PickCake, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerRobot1MoveBlister, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        BlisterPanel1Layout.setVerticalGroup(
            BlisterPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlisterPanel1Layout.createSequentialGroup()
                .addGroup(BlisterPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(spinnerRobot1PickCake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BlisterPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(spinnerRobot1MoveBlister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        spinnerRobot1PickCake.getAccessibleContext().setAccessibleName("robotpickcake");

        ResetButton.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        ResetButton.setBorder(null);
        ResetButton.setLabel("Reset Default Values");
        ResetButton.setName("reset"); // NOI18N
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ControlTabLayout = new javax.swing.GroupLayout(ControlTab);
        ControlTab.setLayout(ControlTabLayout);
        ControlTabLayout.setHorizontalGroup(
            ControlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ControlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ControlTabLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(ControlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ControlTabLayout.createSequentialGroup()
                            .addComponent(ResetButton, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(ControlTabLayout.createSequentialGroup()
                            .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(StopButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControlTabLayout.createSequentialGroup()
                            .addComponent(CakePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(ControlTabLayout.createSequentialGroup()
                            .addComponent(BlisterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControlTabLayout.createSequentialGroup()
                            .addGroup(ControlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(BlisterPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(QualityPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(10, 10, 10))
                        .addGroup(ControlTabLayout.createSequentialGroup()
                            .addComponent(EmergencyButton, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addContainerGap()))))
        );
        ControlTabLayout.setVerticalGroup(
            ControlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControlTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CakePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BlisterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QualityPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BlisterPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ControlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(EmergencyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TabbedPane.addTab("Control", ControlTab);

        LastExecution.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Last Execution:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jLabel7.setForeground(new java.awt.Color(0, 153, 51));
        jLabel7.setText("Correct Blisters:");

        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setText("Defectuous Blisters:");

        okblisters.setText("jLabel3");

        koblisters.setText("jLabel4");

        javax.swing.GroupLayout LastExecutionLayout = new javax.swing.GroupLayout(LastExecution);
        LastExecution.setLayout(LastExecutionLayout);
        LastExecutionLayout.setHorizontalGroup(
            LastExecutionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LastExecutionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LastExecutionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LastExecutionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(koblisters)
                    .addComponent(okblisters))
                .addGap(25, 25, 25))
        );
        LastExecutionLayout.setVerticalGroup(
            LastExecutionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LastExecutionLayout.createSequentialGroup()
                .addGroup(LastExecutionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(okblisters))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LastExecutionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(koblisters)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        History.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "History:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("Defectuous Cakes:");

        jLabel6.setForeground(new java.awt.Color(0, 153, 51));
        jLabel6.setText("Correct Cakes:");

        okcake.setText("jLabel9");

        kocake.setText("jLabel10");

        javax.swing.GroupLayout HistoryLayout = new javax.swing.GroupLayout(History);
        History.setLayout(HistoryLayout);
        HistoryLayout.setHorizontalGroup(
            HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addGroup(HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(okcake)
                    .addComponent(kocake))
                .addGap(21, 21, 21))
        );
        HistoryLayout.setVerticalGroup(
            HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HistoryLayout.createSequentialGroup()
                .addGroup(HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(okcake))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kocake))
                .addContainerGap())
        );

        CakePanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Executions:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jLabel19.setForeground(new java.awt.Color(153, 0, 0));
        jLabel19.setText("Stops:");

        jLabel20.setForeground(new java.awt.Color(0, 153, 51));
        jLabel20.setText("Starts:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 2, 13));
        jLabel21.setForeground(new java.awt.Color(153, 0, 0));
        jLabel21.setText("Emergency Stops:");

        starts.setText("jLabel16");

        stops.setText("jLabel27");

        emerstops.setText("jLabel28");

        jLabel29.setText("Clock Cicles:");

        cicles.setText("230");

        jLabel31.setText("Time Since Last Startup:");

        timelaststartup.setText("jLabel32");

        workingtime.setText("jLabel34");

        jLabel33.setText("Working time:");

        javax.swing.GroupLayout CakePanel3Layout = new javax.swing.GroupLayout(CakePanel3);
        CakePanel3.setLayout(CakePanel3Layout);
        CakePanel3Layout.setHorizontalGroup(
            CakePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CakePanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CakePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CakePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(CakePanel3Layout.createSequentialGroup()
                            .addGroup(CakePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CakePanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addGap(55, 55, 55))
                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE))
                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                        .addComponent(jLabel31)
                        .addComponent(jLabel33))
                    .addGroup(CakePanel3Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(104, 104, 104)))
                .addGroup(CakePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(CakePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(starts)
                        .addComponent(stops))
                    .addComponent(emerstops)
                    .addComponent(timelaststartup)
                    .addComponent(workingtime)
                    .addComponent(cicles))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        CakePanel3Layout.setVerticalGroup(
            CakePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CakePanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(CakePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(starts))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CakePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stops))
                .addGap(7, 7, 7)
                .addGroup(CakePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emerstops))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(CakePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(cicles))
                .addGap(18, 18, 18)
                .addGroup(CakePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(timelaststartup))
                .addGap(20, 20, 20)
                .addGroup(CakePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(workingtime))
                .addContainerGap())
        );

        cicles.getAccessibleContext().setAccessibleName("230");

        GeneratePDF.setFont(new java.awt.Font("Tahoma", 1, 13));
        GeneratePDF.setText("Generate PDF Summary");
        GeneratePDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneratePDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ControlTab1Layout = new javax.swing.GroupLayout(ControlTab1);
        ControlTab1.setLayout(ControlTab1Layout);
        ControlTab1Layout.setHorizontalGroup(
            ControlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlTab1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ControlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ControlTab1Layout.createSequentialGroup()
                        .addComponent(LastExecution, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(ControlTab1Layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControlTab1Layout.createSequentialGroup()
                        .addGroup(ControlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CakePanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(History, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(ControlTab1Layout.createSequentialGroup()
                        .addComponent(GeneratePDF, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                        .addGap(9, 9, 9))))
        );
        ControlTab1Layout.setVerticalGroup(
            ControlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlTab1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(LastExecution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(History, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(CakePanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GeneratePDF, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Report", ControlTab1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPane)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("CakechuffControlPanel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void spinnerChocStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerChocStateChanged
_cakeSubState.setValve2_open_secs(Float.parseFloat(""+spinnerChoc.getValue()));
    	// jSpinnerValve2.setValue(0);
}//GEN-LAST:event_spinnerChocStateChanged

private void spinnerbeltLenght1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerbeltLenght1StateChanged
_cakeSubState.setValve1_open_secs(Float.parseFloat(""+spinnerBeltLenght1.getValue()));
        // jSpinnerValve1.setValue(0);
}//GEN-LAST:event_spinnerbeltLenght1StateChanged

private void spinnerBeltLenght1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerBeltLenght1StateChanged
// TODO add your handling code here:
}//GEN-LAST:event_spinnerBeltLenght1StateChanged

private void spinnerCakesCapacityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerCakesCapacityStateChanged
// TODO add your handling code here:
}//GEN-LAST:event_spinnerCakesCapacityStateChanged

private void spinnerBeltspeed2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerBeltspeed2StateChanged
// TODO add your handling code here:
}//GEN-LAST:event_spinnerBeltspeed2StateChanged

private void spinnerbeltlenght2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerbeltlenght2StateChanged
// TODO add your handling code here:
}//GEN-LAST:event_spinnerbeltlenght2StateChanged

private void spinnerBeltspeed3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerBeltspeed3StateChanged
// TODO add your handling code here:
}//GEN-LAST:event_spinnerBeltspeed3StateChanged

private void spinnerbeltlenght3Changed(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerbeltlenght3Changed
// TODO add your handling code here:
}//GEN-LAST:event_spinnerbeltlenght3Changed

private void spinnerRobot1PickStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerRobot1PickStateChanged
// TODO add your handling code here:
}//GEN-LAST:event_spinnerRobot1PickStateChanged

private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
    System.out.println("Pulse start");
}//GEN-LAST:event_StartButtonActionPerformed

private void StopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopButtonActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_StopButtonActionPerformed

private void EmergencyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmergencyButtonActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_EmergencyButtonActionPerformed

private void GeneratePDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneratePDFActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_GeneratePDFActionPerformed

private void spinnerCaramelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerCaramelStateChanged
// TODO add your handling code here:
}//GEN-LAST:event_spinnerCaramelStateChanged

private void spinnerRobot1PickCakeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerRobot1PickCakeStateChanged
   
}//GEN-LAST:event_spinnerRobot1PickCakeStateChanged

private void spinnerRobot1MoveStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerRobot1MoveStateChanged
// TODO add your handling code here:
}//GEN-LAST:event_spinnerRobot1MoveStateChanged

private void spinnerSealingTimeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerSealingTimeStateChanged
// TODO add your handling code here:
}//GEN-LAST:event_spinnerSealingTimeStateChanged

private void spinnerFailureRangeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerFailureRangeStateChanged
// TODO add your handling code here:
}//GEN-LAST:event_spinnerFailureRangeStateChanged

private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_ResetButtonActionPerformed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {                                       
    	_cakeSubState.setConveyor_velocity(Float.parseFloat(""+spinnerBeltSpeed1.getValue()));
    }                                          

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FactoryInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BlisterPanel;
    private javax.swing.JPanel BlisterPanel1;
    private javax.swing.JPanel CakePanel;
    private javax.swing.JPanel CakePanel3;
    private javax.swing.JPanel ControlTab;
    private javax.swing.JPanel ControlTab1;
    private javax.swing.JButton EmergencyButton;
    private javax.swing.JButton GeneratePDF;
    private javax.swing.JPanel History;
    private javax.swing.JPanel LastExecution;
    private javax.swing.JPanel QualityPanel;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton StartButton;
    private javax.swing.JButton StopButton;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JLabel cicles;
    private javax.swing.JLabel emerstops;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel koblisters;
    private javax.swing.JLabel kocake;
    private javax.swing.JLabel okblisters;
    private javax.swing.JLabel okcake;
    private javax.swing.JSpinner spinnerBeltLenght1;
    private javax.swing.JSpinner spinnerBeltLenght2;
    private javax.swing.JSpinner spinnerBeltLenght3;
    private javax.swing.JSpinner spinnerBeltSpeed1;
    private javax.swing.JSpinner spinnerBeltSpeed2;
    private javax.swing.JSpinner spinnerBeltSpeed3;
    private javax.swing.JSpinner spinnerCakesCapacity;
    private javax.swing.JSpinner spinnerCaramel;
    private javax.swing.JSpinner spinnerChoc;
    private javax.swing.JSpinner spinnerFailRange;
    private javax.swing.JSpinner spinnerRobot1MoveBlister;
    private javax.swing.JSpinner spinnerRobot1PickCake;
    private javax.swing.JSpinner spinnerRobot2Pick;
    private javax.swing.JSpinner spinnerSealingTIme;
    private javax.swing.JLabel starts;
    private javax.swing.JLabel stops;
    private javax.swing.JLabel timelaststartup;
    private javax.swing.JLabel workingtime;
    // End of variables declaration//GEN-END:variables

	@Override
	public void update(Observable arg0, Object arg1) {}
        

    /*@Override
    public java.awt.Image getIconImage() {
        java.awt.Image retValue = java.awt.Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("cc/Images/iconCakeChuff.png"));
        return retValue;
    }*/

}
