/*
 * ConfirmationWindow.java
 *
 * Created on 27 de abril de 2009, 22:18
 */

package cc.simulation.state;

import javax.swing.ImageIcon;

import cc.scada.*;

/**
 * Implementation of the confirmation window of the graphical user interface
 * @version 1.0, 29/05/09
 * @author CaKeChuff team
 */
public class ConfirmationWindow extends javax.swing.JFrame {

    private SCADA _scada;
    private ControlInterface _ui;
    
    /** Creates new form ConfirmationWindow
     * @param s The SCADA
     * @param c The control interface
     * @return The confirmation window
     */
    public ConfirmationWindow(SCADA s, ControlInterface c) {
        _scada =s;
        _ui =c;
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/cc/images/iconCakeChuff.png")).getImage());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        yesbutton = new javax.swing.JButton();
        nobutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Confirmation Window");
        setAlwaysOnTop(true);
        setName("ConfirmationWindow"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html> <P Align=\"center\">Are you sure you want to reset all default<br><br> values of CakeChuff?</p>");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cc/images/warning.PNG"))); // NOI18N

        yesbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cc/Images/ok.PNG"))); // NOI18N
        yesbutton.setText("YES");
        yesbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesbuttonActionPerformed(evt);
            }
        });

        nobutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cc/images/ko.PNG"))); // NOI18N
        nobutton.setText("NO");
        nobutton.setIconTextGap(8);
        nobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nobuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(yesbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(nobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yesbutton)
                            .addComponent(nobutton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel2)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("Confirmation Window");

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void yesbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesbuttonActionPerformed
    this._scada.resetDB();

    _ui.updateValues();
   
    _ui.setEnabled(true);
    this.dispose();
}//GEN-LAST:event_yesbuttonActionPerformed

private void nobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nobuttonActionPerformed
    _ui.setEnabled(true);
    this.dispose();
}//GEN-LAST:event_nobuttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton nobutton;
    private javax.swing.JButton yesbutton;
    // End of variables declaration//GEN-END:variables

}
